site_name: Atlana

docs_dir: docs

nav:
    - 'index.md'
    - 'about.md'

theme:
  name: readthedocs
  custom_dir: docs_theme_override

copyright: All Rights Reserved  

markdown_extensions:
    - toc:
        permalink: True
